# Generated by Django 5.2.15 on 2026-06-11 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AidProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("FEDERAL", "Federal"),
                            ("STATE", "State"),
                            ("INSTITUTIONAL", "Institutional"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "aid_type",
                    models.CharField(
                        choices=[
                            ("GRANT", "Grant"),
                            ("SCHOLARSHIP", "Scholarship"),
                            ("LOAN", "Loan"),
                            ("WORKSTUDY", "Work-study"),
                        ],
                        max_length=12,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AidYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=9, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="AidAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount_offered",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "amount_accepted",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OFFERED", "Offered"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                        ],
                        default="OFFERED",
                        max_length=10,
                    ),
                ),
                ("offered_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aid_awards",
                        to="core.person",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="awards",
                        to="finaid.aidprogram",
                    ),
                ),
                (
                    "aid_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="awards",
                        to="finaid.aidyear",
                    ),
                ),
            ],
            options={
                "ordering": ["-offered_at"],
            },
        ),
        migrations.CreateModel(
            name="Disbursement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("DISBURSED", "Disbursed"),
                        ],
                        default="SCHEDULED",
                        max_length=10,
                    ),
                ),
                ("disbursed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "award",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disbursements",
                        to="finaid.aidaward",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
