# Generated by Django 5.2.15 on 2026-06-11 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("finaid", "0001_initial"),
        ("student_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="disbursement",
            name="ledger_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="student_accounts.ledgerentry",
            ),
        ),
        migrations.AddField(
            model_name="disbursement",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="academics.term",
            ),
        ),
    ]
