# Generated by Django 5.2.15 on 2026-06-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("INQUIRY", "Inquiry"),
                            ("APPLIED", "Applied"),
                            ("IN_REVIEW", "In review"),
                            ("ADMITTED", "Admitted"),
                            ("WAITLISTED", "Waitlisted"),
                            ("DENIED", "Denied"),
                            ("DEPOSITED", "Deposited"),
                            ("ENROLLED", "Enrolled"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        db_index=True,
                        default="INQUIRY",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("deposit_paid_at", models.DateTimeField(blank=True, null=True)),
                ("high_school", models.CharField(blank=True, max_length=120)),
                (
                    "gpa_reported",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("WEB", "Web"),
                            ("FAIR", "College fair"),
                            ("REFERRAL", "Referral"),
                            ("TRANSFER", "Transfer"),
                        ],
                        default="WEB",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("required", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("MISSING", "Missing"),
                            ("RECEIVED", "Received"),
                            ("WAIVED", "Waived"),
                        ],
                        default="MISSING",
                        max_length=10,
                    ),
                ),
                ("received_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CommunicationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("PHONE", "Phone"),
                            ("VISIT", "Visit"),
                            ("TEXT", "Text"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("IN", "Inbound"), ("OUT", "Outbound")],
                        default="OUT",
                        max_length=3,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("occurred_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
    ]
