# Generated by Django 5.2.15 on 2026-06-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlumniInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("class_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("degree_received", models.CharField(blank=True, max_length=80)),
                ("employer", models.CharField(blank=True, max_length=120)),
                ("job_title", models.CharField(blank=True, max_length=120)),
                ("do_not_solicit", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "alumni info",
            },
        ),
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=120)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gift_date", models.DateField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CHECK", "Check"),
                            ("CARD", "Card"),
                            ("STOCK", "Stock"),
                            ("CASH", "Cash"),
                            ("PAYROLL", "Payroll deduction"),
                        ],
                        default="CHECK",
                        max_length=10,
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-gift_date"],
            },
        ),
        migrations.CreateModel(
            name="Pledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField()),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUAL", "Annual"),
                            ("ONE_TIME", "One-time"),
                        ],
                        default="ONE_TIME",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("FULFILLED", "Fulfilled"),
                            ("DEFAULTED", "Defaulted"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
    ]
