# Generated by Django 5.2.15 on 2026-06-11 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("advancement", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumniinfo",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alumni_info",
                to="core.person",
            ),
        ),
        migrations.AddField(
            model_name="gift",
            name="designation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gifts",
                to="advancement.designation",
            ),
        ),
        migrations.AddField(
            model_name="gift",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gifts",
                to="core.person",
            ),
        ),
        migrations.AddField(
            model_name="pledge",
            name="designation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pledges",
                to="advancement.designation",
            ),
        ),
        migrations.AddField(
            model_name="pledge",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pledges",
                to="core.person",
            ),
        ),
        migrations.AddField(
            model_name="gift",
            name="pledge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gifts",
                to="advancement.pledge",
            ),
        ),
    ]
