# Generated by Django 5.2.15 on 2026-06-11 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clearanceitem",
            name="cleared_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clearanceitem",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.department",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollments",
                to="core.person",
            ),
        ),
        migrations.AddField(
            model_name="graduationapplication",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="graduation_applications",
                to="core.person",
            ),
        ),
        migrations.AddField(
            model_name="clearanceitem",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clearance_items",
                to="academics.graduationapplication",
            ),
        ),
        migrations.AddField(
            model_name="programrequirement",
            name="applicable_courses",
            field=models.ManyToManyField(blank=True, to="academics.course"),
        ),
        migrations.AddField(
            model_name="programrequirement",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="academics.program",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sections",
                to="academics.course",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sections_taught",
                to="core.person",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollments",
                to="academics.section",
            ),
        ),
        migrations.AddField(
            model_name="studentprogram",
            name="advisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advisees",
                to="core.person",
            ),
        ),
        migrations.AddField(
            model_name="studentprogram",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_programs",
                to="core.person",
            ),
        ),
        migrations.AddField(
            model_name="studentprogram",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="academics.program",
            ),
        ),
        migrations.AddField(
            model_name="graduationapplication",
            name="student_program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="graduation_applications",
                to="academics.studentprogram",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="academics.subject",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sections",
                to="academics.term",
            ),
        ),
        migrations.AddField(
            model_name="graduationapplication",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="graduation_applications",
                to="academics.term",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("person", "section"), name="uniq_enrollment"
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("subject", "number"), name="uniq_course_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("course", "term", "section_number"), name="uniq_section"
            ),
        ),
    ]
